In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

In [2]:
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

In [3]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [5]:
df.index.name

In [6]:
df.index.name = 'job_index'

In [7]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [8]:
df.index.dtype

dtype('int64')

In [9]:
df_egypt = df[df['job_country'] == 'Egypt']

In [10]:
df_egypt

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
83,Software Engineer,Senior DevOps Engineer,Egypt (+1 other),via Levels.fyi,Full-time,False,Egypt,2023-11-01 13:13:36,False,False,Egypt,NaN,NaN,NaN,2U,"['bash', 'python', 'aws', 'linux', 'splunk', '...","{'analyst_tools': ['splunk'], 'cloud': ['aws']..."
1320,Software Engineer,Integration Engineer,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-07-21 13:43:21,False,False,Egypt,NaN,NaN,NaN,Ericsson,"['go', 'node']","{'programming': ['go'], 'webframeworks': ['nod..."
1362,Machine Learning Engineer,Machine learning engineer,Egypt,via Indeed,Full-time,False,Egypt,2023-02-28 13:39:47,False,False,Egypt,NaN,NaN,NaN,IQVIA,NaN,NaN
1567,Data Analyst,Data Analyst,Egypt,via Egypt.tanqeeb.com,Full-time,False,Egypt,2023-11-05 13:53:44,True,False,Egypt,NaN,NaN,NaN,Al Asdekaa Group for Dai,['python'],{'programming': ['python']}
2981,Senior Data Analyst,Senior Data Business Analyst,Egypt,via LinkedIn,Full-time,False,Egypt,2023-12-17 13:18:00,False,False,Egypt,NaN,NaN,NaN,FlairsTech,"['sql', 'python', 'r', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785550,Data Engineer,Data Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,True,False,Egypt,NaN,NaN,NaN,On-Hire,NaN,NaN
785554,Senior Data Engineer,Senior Database Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,False,False,Egypt,NaN,NaN,NaN,MigrationIT,"['sql', 'sql server', 'postgresql', 'mysql', '...","{'cloud': ['oracle'], 'databases': ['sql serve..."
785558,Business Analyst,Marketing Analyst,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:18,False,False,Egypt,NaN,NaN,NaN,Informa Markets,"['outlook', 'sheets', 'excel', 'power bi', 'ta...","{'analyst_tools': ['outlook', 'sheets', 'excel..."
785587,Business Analyst,Business Intelligence Analyst,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:16,False,False,Egypt,NaN,NaN,NaN,Ingram Micro,"['python', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'progra..."
785686,Business Analyst,Business Analyst,Egypt,via Jobs Trabajo.org,Full-time,False,Egypt,2023-11-20 06:20:34,False,False,Egypt,NaN,NaN,NaN,Sumerge,NaN,NaN

In [11]:
df_egypt.reset_index(inplace=True)

In [12]:
df_egypt

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,83,Software Engineer,Senior DevOps Engineer,Egypt (+1 other),via Levels.fyi,Full-time,False,Egypt,2023-11-01 13:13:36,False,False,Egypt,NaN,NaN,NaN,2U,"['bash', 'python', 'aws', 'linux', 'splunk', '...","{'analyst_tools': ['splunk'], 'cloud': ['aws']..."
1,1320,Software Engineer,Integration Engineer,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-07-21 13:43:21,False,False,Egypt,NaN,NaN,NaN,Ericsson,"['go', 'node']","{'programming': ['go'], 'webframeworks': ['nod..."
2,1362,Machine Learning Engineer,Machine learning engineer,Egypt,via Indeed,Full-time,False,Egypt,2023-02-28 13:39:47,False,False,Egypt,NaN,NaN,NaN,IQVIA,NaN,NaN
3,1567,Data Analyst,Data Analyst,Egypt,via Egypt.tanqeeb.com,Full-time,False,Egypt,2023-11-05 13:53:44,True,False,Egypt,NaN,NaN,NaN,Al Asdekaa Group for Dai,['python'],{'programming': ['python']}
4,2981,Senior Data Analyst,Senior Data Business Analyst,Egypt,via LinkedIn,Full-time,False,Egypt,2023-12-17 13:18:00,False,False,Egypt,NaN,NaN,NaN,FlairsTech,"['sql', 'python', 'r', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2927,785550,Data Engineer,Data Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,True,False,Egypt,NaN,NaN,NaN,On-Hire,NaN,NaN
2928,785554,Senior Data Engineer,Senior Database Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,False,False,Egypt,NaN,NaN,NaN,MigrationIT,"['sql', 'sql server', 'postgresql', 'mysql', '...","{'cloud': ['oracle'], 'databases': ['sql serve..."
2929,785558,Business Analyst,Marketing Analyst,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:18,False,False,Egypt,NaN,NaN,NaN,Informa Markets,"['outlook', 'sheets', 'excel', 'power bi', 'ta...","{'analyst_tools': ['outlook', 'sheets', 'excel..."
2930,785587,Business Analyst,Business Intelligence Analyst,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:16,False,False,Egypt,NaN,NaN,NaN,Ingram Micro,"['python', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'progra..."
2931,785686,Business Analyst,Business Analyst,Egypt,via Jobs Trabajo.org,Full-time,False,Egypt,2023-11-20 06:20:34,False,False,Egypt,NaN,NaN,NaN,Sumerge,NaN,NaN

In [13]:
df_egypt.set_index('job_index' , inplace=True)

In [14]:
df_egypt

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
83,Software Engineer,Senior DevOps Engineer,Egypt (+1 other),via Levels.fyi,Full-time,False,Egypt,2023-11-01 13:13:36,False,False,Egypt,NaN,NaN,NaN,2U,"['bash', 'python', 'aws', 'linux', 'splunk', '...","{'analyst_tools': ['splunk'], 'cloud': ['aws']..."
1320,Software Engineer,Integration Engineer,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-07-21 13:43:21,False,False,Egypt,NaN,NaN,NaN,Ericsson,"['go', 'node']","{'programming': ['go'], 'webframeworks': ['nod..."
1362,Machine Learning Engineer,Machine learning engineer,Egypt,via Indeed,Full-time,False,Egypt,2023-02-28 13:39:47,False,False,Egypt,NaN,NaN,NaN,IQVIA,NaN,NaN
1567,Data Analyst,Data Analyst,Egypt,via Egypt.tanqeeb.com,Full-time,False,Egypt,2023-11-05 13:53:44,True,False,Egypt,NaN,NaN,NaN,Al Asdekaa Group for Dai,['python'],{'programming': ['python']}
2981,Senior Data Analyst,Senior Data Business Analyst,Egypt,via LinkedIn,Full-time,False,Egypt,2023-12-17 13:18:00,False,False,Egypt,NaN,NaN,NaN,FlairsTech,"['sql', 'python', 'r', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785550,Data Engineer,Data Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,True,False,Egypt,NaN,NaN,NaN,On-Hire,NaN,NaN
785554,Senior Data Engineer,Senior Database Engineer,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:28,False,False,Egypt,NaN,NaN,NaN,MigrationIT,"['sql', 'sql server', 'postgresql', 'mysql', '...","{'cloud': ['oracle'], 'databases': ['sql serve..."
785558,Business Analyst,Marketing Analyst,"Cairo, Egypt",via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:18,False,False,Egypt,NaN,NaN,NaN,Informa Markets,"['outlook', 'sheets', 'excel', 'power bi', 'ta...","{'analyst_tools': ['outlook', 'sheets', 'excel..."
785587,Business Analyst,Business Intelligence Analyst,Egypt,via Trabajo.org,Full-time,False,Egypt,2023-12-07 06:20:16,False,False,Egypt,NaN,NaN,NaN,Ingram Micro,"['python', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'progra..."
785686,Business Analyst,Business Analyst,Egypt,via Jobs Trabajo.org,Full-time,False,Egypt,2023-11-20 06:20:34,False,False,Egypt,NaN,NaN,NaN,Sumerge,NaN,NaN

In [18]:
median_pivot = df_egypt.pivot_table(
    values='salary_year_avg',
    index='job_title_short',
    aggfunc=['median','min','max']
)

In [19]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Analyst                     54257.00         50400.0         75550.0
Data Engineer                    87986.50         45000.0        147500.0
Data Scientist                   98554.75         70000.0        157500.0
Machine Learning Engineer       119000.00         72000.0        166000.0
Senior Data Engineer             96773.00         96773.0         96773.0
Senior Data Scientist            88128.00         79200.0         90670.0

In [21]:
#the by is tuple because we have two levels of naming
median_pivot.sort_values(by=('median' , 'salary_year_avg') , ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Machine Learning Engineer       119000.00         72000.0        166000.0
Data Scientist                   98554.75         70000.0        157500.0
Senior Data Engineer             96773.00         96773.0         96773.0
Senior Data Scientist            88128.00         79200.0         90670.0
Data Engineer                    87986.50         45000.0        147500.0
Data Analyst                     54257.00         50400.0         75550.0

In [22]:
median_pivot.sort_index()

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Analyst                     54257.00         50400.0         75550.0
Data Engineer                    87986.50         45000.0        147500.0
Data Scientist                   98554.75         70000.0        157500.0
Machine Learning Engineer       119000.00         72000.0        166000.0
Senior Data Engineer             96773.00         96773.0         96773.0
Senior Data Scientist            88128.00         79200.0         90670.0

In [23]:
median_pivot.sort_values(by='job_title_short')

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Analyst                     54257.00         50400.0         75550.0
Data Engineer                    87986.50         45000.0        147500.0
Data Scientist                   98554.75         70000.0        157500.0
Machine Learning Engineer       119000.00         72000.0        166000.0
Senior Data Engineer             96773.00         96773.0         96773.0
Senior Data Scientist            88128.00         79200.0         90670.0